# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8746ec04a371bac4d468708b73cbe104a7060ca700302c46ed15a674f474d44d8591e62f7dc5043cb2d3be8bdff8981ed6b556408606ca0cd06bd97a2631a175

test:
  secret_key_base: d368c3027e6f2cc7ec0cd98be311341b99f88e4ceff77729d86aa77277a868fa42a3e1bbe4d17621f10e15180a32b9627785ecdee6afdce653927f06629ca8a7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
